### ISSUE TITLE
Upgrade to Node.js 20

### ISSUE THREAD

**Issue by jaroslavlibal** [supplypike/setup-bin#364]
Hello,

we are receiving warnings in Github Actions related to the Node.js version:

`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20.`

This is the last repository (that we use) that does not have a new version with such support. Since I don't have enough experience with Node.js, could someone more experienced help to responsibly handle this upgrade, please?

Thanks!

**Comment by donatj** [comment]
Came here to make the same request. Getting the same notice.

**Comment by HarryGogonis** [comment]
released in [v4](https://github.com/supplypike/setup-bin/releases/tag/v4)
