### ISSUE TITLE
v4 did not set binary correct permission

### ISSUE THREAD

**Issue by billzhuang** [supplypike/setup-bin#377]
hi,
    after use v4, my gh action report can not find the binary, which did not happen in v3

**Comment by billzhuang** [comment]
-rw-r--r--+ 1 runner docker 23711744 Apr 10 03:45 kubectl-neat-diff

chmod failed

**Comment by anagyzambo-kx** [comment]
I think the change from `chmodr` to `fs.chmod()` is not a drop-in replacement as `chmodr` works recursively on the path whereas `fs.chmod()` works on a single file system entity.

See: https://www.npmjs.com/package/chmodr

**Comment by christophkloeffel** [comment]
+1 
I also experience this issue.
